import IC_HOME_ON from 'assets/images/ic_home.png';
import IC_HOME_OFF from 'assets/images/ic_home_off.png';

// import IC_EVENT from 'assets/images/ic_event.png';
import IC_PERSON_OFF from 'assets/images/ic_person.png';
import IC_PERSON_ON from 'assets/images/ic_person_on.png';

import IC_FACE_OFF from 'assets/images/ic_face.png';
import IC_FACE_ON from 'assets/images/ic_face_on.png';

import { Menu } from 'types/types';
import { IC_MSG, IC_CHAT_ON, IC_CHAT_OF } from '@assets/index';

enum RequestMethod {
  POST = 'POST',
  PATCH = 'PATCH',
  GET = 'GET',
}

const listMenu: Array<Menu> = Array(
  {
    iconOn: IC_HOME_ON,
    iconOff: IC_HOME_OFF,
    name: 'listMenu_home',
    isMenu: false,
  },
  // {
  //   icon: IC_EVENT,
  //   name: 'listMenu_event',
  // },
  {
    iconOn: IC_FACE_ON,
    iconOff: IC_FACE_OFF,
    name: 'listMenu_student',
    isMenu: true,
  },
  {
    iconOn: IC_PERSON_ON,
    iconOff: IC_PERSON_OFF,
    name: 'listMenu_user',
    isMenu: true,
  },
  {
    iconOn: IC_CHAT_ON,
    iconOff: IC_CHAT_OF,
    name: 'msg_headerTitle',
    isMenu: true,
  },
);

const RESET_ALL_STATE = 'RESET_ALL_STATE';
const NAVIGATION_PREFIX = 'NAVIGATION_';

const STATUS_NO_AUTH = 'STATUS_NO_AUTH';
const STATUS_AUTHED = 'STATUS_AUTHED';

//SCREEN
const LOADING_PAGE = `${NAVIGATION_PREFIX}LOADING_PAGE`;
const LAUNCH_SCREEN = `${NAVIGATION_PREFIX}LAUNCH_SCREEN`;
const LOGIN_SCREEN = `${NAVIGATION_PREFIX}LOGIN_SCREEN`;
const SIGNUP_SCREEN = `${NAVIGATION_PREFIX}SIGNUP_SCREEN`;
const SIDE_MENU = `${NAVIGATION_PREFIX}SIDE_MENU`;
const HOME_SCREEN = `${NAVIGATION_PREFIX}NAVIGATION_HOME_SCREEN`;
const USER_PROFILE = `${NAVIGATION_PREFIX}NAVIGATION_USER_PROFILE`;
const CHANGEPASS_SCREEN = `${NAVIGATION_PREFIX}NAVIGATION_CHANGEPASS_SCREEN`;
const STUDENT_LIST = `${NAVIGATION_PREFIX}NAVIGATION_STUDENT_LIST`;
const PARENT_MEETING = `${NAVIGATION_PREFIX}NAVIGATION_PARENT_MEETING`;
const STUDENT_PROFILE = `${NAVIGATION_PREFIX}NAVIGATION_STUDENT_PROFILE`;
const STUDENT_REPORT = `${NAVIGATION_PREFIX}NAVIGATION_STUDENT_REPORT`;
const FORGOT_PASSWORD_SCREEN = `${NAVIGATION_PREFIX}FORGOT_PASSWORD_SCREEN`;
const ENTER_PASSWORD_SCREEN = `${NAVIGATION_PREFIX}ENTER_PASSWORD_SCREEN`;
const PDF_SCREEN = `${NAVIGATION_PREFIX}PDF_SCREEN`;
const NOTIFICATION_LIST = `${NAVIGATION_PREFIX}NOTIFICATION_LIST`;
const NOTIFICATION_DETAIL = `${NAVIGATION_PREFIX}NOTIFICATION_DETAIL`;
const MESSAGE_SCREEN = `${NAVIGATION_PREFIX}MESSAGE_SCREEN`;
const CHAT_SCREEN = `${NAVIGATION_PREFIX}CHAT_SCREEN`;
const SEARCH_SCREEN = `${NAVIGATION_PREFIX}SEARCH_SCREEN`;
const CHAT_GROUP_SCREEN = `${NAVIGATION_PREFIX}CHAT_GROUP_SCREEN`;
const ANNOUNCEMENT = `${NAVIGATION_PREFIX}ANNOUNCEMENT`;
const STUDENT_INFORMATION = `${NAVIGATION_PREFIX}STUDENT_INFORMATION`;
const MEAL_SCREEN = `${NAVIGATION_PREFIX}MEAL_SCREEN`;
const ATTENDANCE_SCREEN = `${NAVIGATION_PREFIX}ATTENDANCE_SCREEN`;
const BEHAVIOR_POINT_SCREEN = `${NAVIGATION_PREFIX}BEHAVIOR_POINT_SCREEN`;

const NAVIGATION_ROOT_WITH_SAGA = 'NAVIGATION_ROOT_WITH_SAGA';
const NAVIGATION_ROOT_SUCCESS = 'NAVIGATION_ROOT_SUCCESS';
const SELECTED_MENU = 'SELECTED_MENU';
const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
const CHANGE_LANGUAGE_WITH_SAGA = 'CHANGE_LANGUAGE_WITH_SAGA';

const LOGIN_WITH_SAGA = 'LOGIN_WITH_SAGA';
const LOGIN_WITH_SAGA_SUCCESS = 'LOGIN_WITH_SAGA_SUCCESS';
const LOGIN_WITH_SAGA_FAILED = 'LOGIN_WITH_SAGA_FAILED';
const LOGOUT_WITH_SAGA = 'LOGOUT_WITH_SAGA';
const VERIFY_CODE_SCREEN = 'VERIFY_CODE_SCREEN';
const VERIFY_CODE_REGISTER_WITH_SAGA = 'VERIFY_CODE_REGISTER_WITH_SAGA';
const VERIFY_CODE_REGISTER_WITH_SAGA_FAILED = 'VERIFY_CODE_REGISTER_WITH_SAGA_FAILED';
// const VERIFY_CODE_REGISTER_WITH_SAGA_SUCCESS = 'VERIFY_CODE_REGISTER_WITH_SAGA_SUCCESS';
const REGISTER_WITH_SAGA = 'REGISTER_WITH_SAGA';
const REGISTER_WITH_SAGA_SUCCESS = 'REGISTER_WITH_SAGA_SUCCESS';
const REGISTER_WITH_SAGA_FAILED = 'REGISTER_WITH_SAGA_FAILED';
const ENTER_PASSWORD_REGISTER_WITH_SAGA = 'ENTER_PASSWORD_REGISTER_WITH_SAGA';
const ENTER_PASSWORD_REGISTER_WITH_SAGA_FAILED = 'ENTER_PASSWORD_REGISTER_WITH_SAGA_FAILED';
const FORGOT_PASSWORD_WITH_SAGA = 'FORGOT_PASSWORD_WITH_SAGA';
const FORGOT_PASSWORD_WITH_SAGA_SUCCESS = 'FORGOT_PASSWORD_WITH_SAGA_SUCCESS';
const FORGOT_PASSWORD_WITH_SAGA_FAILED = 'FORGOT_PASSWORD_WITH_SAGA_FAILED';
const VERIFY_CODE_FORGOT_PASSWORD_WITH_SAGA = 'VERIFY_CODE_FORGOT_PASSWORD_WITH_SAGA';
const VERIFY_CODE_FORGOT_PASSWORD_WITH_SAGA_FAILED = 'VERIFY_CODE_FORGOT_PASSWORD_WITH_SAGA_FAILED';

const ENTER_PASSWORD_FORGOT_WITH_SAGA = 'ENTER_PASSWORD_FORGOT_WITH_SAGA';
const ENTER_PASSWORD_FORGOT_WITH_SAGA_FAILED = 'ENTER_PASSWORD_FORGOT_WITH_SAGA_FAILED';
const RESET_MESSAGE_FORGOT = 'RESET_MESSAGE_FORGOT';

// STUDENT
const LANGUAGE_WITH_SAGA = 'LANGUAGE_WITH_SAGA';
const LANGUAGE_WITH_SAGA_SUCCESS = 'LANGUAGE_WITH_SAGA_SUCCESS';
const LANGUAGE_WITH_SAGA_FAILED = 'LANGUAGE_WITH_SAGA_FAILED';
const GET_MESSAGE_STUDENT = 'GET_MESSAGE_STUDENT';
const GET_MESSAGE_LIST = 'GET_MESSAGE_LIST';

// STUDENT
const ADD_CURRENT_STUDENT = 'ADD_CURRENT_STUDENT';
const GET_LIST_STUDENTS_SAGA = 'GET_LIST_STUDENTS_SAGA';
const GET_CURRENT_STUDENT_SAGA = 'GET_CURRENT_STUDENT_SAGA';
const GET_LIST_REPORTS_SAGA = 'GET_LIST_REPORTS_SAGA';
const SET_LIST_STUDENTS = 'SET_LIST_STUDENTS';
const SET_CURRENT_STUDENT = 'SET_CURRENT_STUDENT';
const SET_LIST_REPORTS = 'SET_LIST_REPORTS';
const UPDATE_STUDENT_SAGA = 'UPDATE_STUDENT_SAGA';
const RESET_MESSAGE_STUDENT = 'RESET_MESSAGE_STUDENT';
const SET_LIST_SCHOOL_YEAR = 'SET_LIST_SCHOOL_YEAR';
const GET_ALL_LIST_SAGA = 'GET_ALL_LIST_SAGA';
const SET_LIST_PERIOD = 'SET_LIST_PERIOD';
const SET_LIST_TERM = 'SET_LIST_TERM';

// USER
const GET_PROFILE_USER_SAGA = 'GET_PROFILE_USER_SAGA';
const SET_PROFILE_USER = 'SET_PROFILE_USER';
const UPDATE_USER_SAGA = 'UPDATE_USER_SAGA';
const CHANGE_PASSWORD_SAGA = 'CHANGE_PASSWORD_SAGA';
const UPLOAD_AVATAR_SAGA = 'UPLOAD_AVATAR_SAGA';
const GET_MESSAGE_USER = 'GET_MESSAGE_USER';
const RESET_MESSAGE_USER = 'RESET_MESSAGE_USER';
const GET_MESSAGE_CHANGEPASS = 'GET_MESSAGE_CHANGEPASS';
const RESET_MESSAGE_CHANGEPASS = 'RESET_MESSAGE_CHANGEPASS';
const GET_RELATIONSHIP_SAGA = 'GET_RELATIONSHIP_SAGA';
const SET_RELATIONSHIP = 'SET_RELATIONSHIP';

// NOTIFICATION
const NOTIFY_WITH_SAGA = 'NOTIFY_WITH_SAGA';
const NOTIFY_WITH_SAGA_SUCCESS = 'NOTIFY_WITH_SAGA_SUCCESS';
const NOTIFY_WITH_SAGA_FAILED = 'NOTIFY_WITH_SAGA_FAILED';
const CURRENT_NOTIFY_SAGA = 'CURRENT_NOTIFY_SAGA';
const CURRENT_NOTIFY_SAGA_SUCCESS = 'CURRENT_NOTIFY_SAGA_SUCCESS';
const CURRENT_NOTIFY_SAGA_FAILED = 'CURRENT_NOTIFY_SAGA_FAILED';
const NOTIFY_SET_LOADING = 'NOTIFY_SET_LOADING';
const NOTIFY_SET_REFRESH = 'NOTIFY_SET_REFRESH';
const NOTIFY_SET_ICON = 'NOTIFY_SET_ICON';

// EVENT
const EVENT_WITH_SAGA = 'EVENT_WITH_SAGA';
const EVENT_WITH_SAGA_SUCCESS = 'EVENT_WITH_SAGA_SUCCESS';
const EVENT_WITH_SAGA_FAILED = 'EVENT_WITH_SAGA_FAILED';
const EVENT_SET_REFRESH = 'EVENT_SET_REFRESH';
const EVENT_SET_LOADING = 'EVENT_SET_LOADING';

// MESSAGE

const SET_NUMBER_MESSAGE_NOT_SEEN = 'SET_NUMBER_MESSAGE_NOT_SEEN';
const GET_NUMBER_MESSAGE_NOT_SEEN = 'GET_NUMBER_MESSAGE_NOT_SEEN';

//TEACHER
const GET_LIST_TEACHER = 'GET_LIST_TEACHER';
const SET_LIST_TEACHER = 'SET_LIST_TEACHER';

const FILTER_LIST_TEACHER = 'FILTER_LIST_TEACHER';
const FILTER_LIST_TEACHER_SUCCESS = 'FILTER_LIST_TEACHER_SUCCESS';
const FILTER_LIST_TEACHER_FAILED = 'FILTER_LIST_TEACHER_FAILED';

//Firebase
const FILTER_LIST_TEACHER_FIREBASE = 'FILTER_LIST_TEACHER_FIREBASE';
const FILTER_LIST_TEACHER_FIREBASE_SUCCESS = 'FILTER_LIST_TEACHER_FIREBASE_SUCCESS';
const FILTER_LIST_TEACHER_FIREBASE_FAILED = 'FILTER_LIST_TEACHER_FIREBASE_FAILED';
//Attendance
const GET_ATTENDANCE_BY_DAY = 'GET_ATTENDANCE_BY_DAY';
const GET_ATTENDANCE_BY_DAY_SUCCESS = 'GET_ATTENDANCE_BY_DAY_SUCCESS';
const GET_ATTENDANCE_BY_DAY_FAILED = 'GET_ATTENDANCE_BY_DAY_FAILED';

//Meal
const GET_MEAL_BY_DAY = 'GET_MEAL_BY_DAY';
const GET_MEAL_BY_DAY_SUCCESS = 'GET_MEAL_BY_DAY_SUCCESS';
const GET_MEAL_BY_DAY_FAILED = 'GET_MEAL_BY_DAY_FAILED';

//Notification student attendance, meal
const INCREASE_NOT_SEEN_ATTENDANCE = 'INCREASE_NOT_SEEN_ATTENDANCE';
const DECREASE_NOT_SEEN_ATTENDANCE = 'DECREASE_NOT_SEEN_ATTENDANCE';
const INCREASE_NOT_SEEN_MEAL = 'INCREASE_NOT_SEEN_MEAL';
const DECREASE_NOT_SEEN_MEAL = 'DECREASE_NOT_SEEN_MEAL';
const SET_STUDENT_NOTIFICATION = 'SET_STUDENT_NOTIFICATION';

const GET_TIME_RECALL = 'GET_TIME_RECALL';
const GET_TIME_RECALL_SUCCESS = 'GET_TIME_RECALL_SUCCESS';

export {
  listMenu,
  RESET_ALL_STATE,
  RequestMethod,
  LOADING_PAGE,
  LOGIN_SCREEN,
  HOME_SCREEN,
  LAUNCH_SCREEN,
  SIGNUP_SCREEN,
  SIDE_MENU,
  SELECTED_MENU,
  CHANGE_LANGUAGE,
  LOGOUT_WITH_SAGA,
  LOGIN_WITH_SAGA,
  LOGIN_WITH_SAGA_SUCCESS,
  LOGIN_WITH_SAGA_FAILED,
  NAVIGATION_ROOT_WITH_SAGA,
  NAVIGATION_ROOT_SUCCESS,
  STATUS_NO_AUTH,
  STATUS_AUTHED,
  USER_PROFILE,
  CHANGEPASS_SCREEN,
  STUDENT_LIST,
  PARENT_MEETING,
  STUDENT_PROFILE,
  STUDENT_REPORT,
  ADD_CURRENT_STUDENT,
  FORGOT_PASSWORD_SCREEN,
  VERIFY_CODE_SCREEN,
  GET_LIST_STUDENTS_SAGA,
  GET_CURRENT_STUDENT_SAGA,
  GET_LIST_REPORTS_SAGA,
  SET_LIST_STUDENTS,
  SET_CURRENT_STUDENT,
  SET_LIST_REPORTS,
  UPDATE_STUDENT_SAGA,
  GET_PROFILE_USER_SAGA,
  SET_PROFILE_USER,
  UPDATE_USER_SAGA,
  CHANGE_PASSWORD_SAGA,
  GET_MESSAGE_STUDENT,
  UPLOAD_AVATAR_SAGA,
  LANGUAGE_WITH_SAGA,
  LANGUAGE_WITH_SAGA_SUCCESS,
  LANGUAGE_WITH_SAGA_FAILED,
  REGISTER_WITH_SAGA,
  REGISTER_WITH_SAGA_FAILED,
  VERIFY_CODE_REGISTER_WITH_SAGA,
  REGISTER_WITH_SAGA_SUCCESS,
  VERIFY_CODE_REGISTER_WITH_SAGA_FAILED,
  // VERIFY_CODE_REGISTER_WITH_SAGA_SUCCESS,
  ENTER_PASSWORD_SCREEN,
  FORGOT_PASSWORD_WITH_SAGA,
  FORGOT_PASSWORD_WITH_SAGA_SUCCESS,
  FORGOT_PASSWORD_WITH_SAGA_FAILED,
  ENTER_PASSWORD_REGISTER_WITH_SAGA,
  ENTER_PASSWORD_REGISTER_WITH_SAGA_FAILED,
  VERIFY_CODE_FORGOT_PASSWORD_WITH_SAGA,
  VERIFY_CODE_FORGOT_PASSWORD_WITH_SAGA_FAILED,
  ENTER_PASSWORD_FORGOT_WITH_SAGA,
  ENTER_PASSWORD_FORGOT_WITH_SAGA_FAILED,
  GET_MESSAGE_USER,
  RESET_MESSAGE_USER,
  RESET_MESSAGE_STUDENT,
  PDF_SCREEN,
  NOTIFICATION_LIST,
  NOTIFICATION_DETAIL,
  NOTIFY_WITH_SAGA,
  NOTIFY_WITH_SAGA_SUCCESS,
  NOTIFY_WITH_SAGA_FAILED,
  CURRENT_NOTIFY_SAGA,
  CURRENT_NOTIFY_SAGA_SUCCESS,
  CURRENT_NOTIFY_SAGA_FAILED,
  GET_MESSAGE_LIST,
  EVENT_WITH_SAGA,
  EVENT_WITH_SAGA_SUCCESS,
  EVENT_WITH_SAGA_FAILED,
  SET_LIST_SCHOOL_YEAR,
  GET_ALL_LIST_SAGA,
  SET_LIST_PERIOD,
  SET_LIST_TERM,
  RESET_MESSAGE_FORGOT,
  GET_MESSAGE_CHANGEPASS,
  RESET_MESSAGE_CHANGEPASS,
  CHANGE_LANGUAGE_WITH_SAGA,
  EVENT_SET_REFRESH,
  EVENT_SET_LOADING,
  NOTIFY_SET_LOADING,
  NOTIFY_SET_REFRESH,
  NOTIFY_SET_ICON,
  GET_RELATIONSHIP_SAGA,
  SET_RELATIONSHIP,
  MESSAGE_SCREEN,
  CHAT_SCREEN,
  SEARCH_SCREEN,
  SET_NUMBER_MESSAGE_NOT_SEEN,
  GET_NUMBER_MESSAGE_NOT_SEEN,
  GET_LIST_TEACHER,
  SET_LIST_TEACHER,
  FILTER_LIST_TEACHER,
  FILTER_LIST_TEACHER_SUCCESS,
  FILTER_LIST_TEACHER_FAILED,
  FILTER_LIST_TEACHER_FIREBASE,
  FILTER_LIST_TEACHER_FIREBASE_SUCCESS,
  FILTER_LIST_TEACHER_FIREBASE_FAILED,
  CHAT_GROUP_SCREEN,
  ANNOUNCEMENT,
  STUDENT_INFORMATION,
  MEAL_SCREEN,
  ATTENDANCE_SCREEN,
  BEHAVIOR_POINT_SCREEN,
  GET_ATTENDANCE_BY_DAY,
  GET_ATTENDANCE_BY_DAY_SUCCESS,
  GET_ATTENDANCE_BY_DAY_FAILED,
  GET_MEAL_BY_DAY,
  GET_MEAL_BY_DAY_SUCCESS,
  GET_MEAL_BY_DAY_FAILED,
  INCREASE_NOT_SEEN_ATTENDANCE,
  DECREASE_NOT_SEEN_ATTENDANCE,
  INCREASE_NOT_SEEN_MEAL,
  DECREASE_NOT_SEEN_MEAL,
  SET_STUDENT_NOTIFICATION,
  GET_TIME_RECALL,
  GET_TIME_RECALL_SUCCESS,
};
